import { AgentMapRow } from "./types";

export const agentMapRows: AgentMapRow[] = [
  {
    id: "sales-deal-priority",
    category: "Sales / Revenue",
    function: "Prioritize revenue-bearing conversations and partnerships",
    candidateAgent: "Pipeline Priority Copilot",
    currentOwner: "Founder",
    status: "human_plus_ai",
    priority: "now",
    strategicImportance: "critical",
    requiredInputs: ["Inbound leads", "Partnership notes", "Deal stage snapshot", "Revenue potential"],
    expectedOutputs: ["Ranked priority list", "Next-action suggestions", "Blocked deal watchlist"],
    notes: "Sales clarity is the highest immediate planning need. Keep human-owned; AI should only structure and prioritize.",
  },
  {
    id: "sales-listing-packaging",
    category: "Sales / Revenue",
    function: "Package the best listings into sponsorable or promotable inventory",
    candidateAgent: "Listing Packaging Assistant",
    currentOwner: "Founder + editorial",
    status: "candidate_for_agent",
    priority: "next",
    strategicImportance: "high",
    requiredInputs: ["Agent V1 selections", "Listing trust signals", "Commercial context", "Pricing notes"],
    expectedOutputs: ["Shortlist of commercially interesting listings", "Packaging notes", "Sales-ready rationale"],
    notes: "Depends on trustworthy listing selection, but should remain review-first and non-automated.",
  },
  {
    id: "sales-offer-tracking",
    category: "Sales / Revenue",
    function: "Track active offers, asks, and monetization experiments",
    candidateAgent: "Revenue Tracker",
    currentOwner: "Founder",
    status: "human_only",
    priority: "now",
    strategicImportance: "critical",
    requiredInputs: ["Current offer list", "Pricing assumptions", "Outbound experiments", "Partner responses"],
    expectedOutputs: ["Current revenue map", "Offer status notes", "Decision prompts"],
    notes: "This is planning-critical even if it stays manual for now.",
  },
  {
    id: "data-source-triage",
    category: "Data / Source Ops",
    function: "Triage source health and decide what needs cleanup attention",
    candidateAgent: "Source Triage Assistant",
    currentOwner: "Ingestion / cleanup track",
    status: "human_plus_ai",
    priority: "now",
    strategicImportance: "high",
    requiredInputs: ["Source status", "Approval rates", "Image coverage", "Recent failures"],
    expectedOutputs: ["Triage queue", "Recovery candidates", "Low-trust source watchlist"],
    notes: "Separate from Agent V1. Useful for prioritization, not blocking selector work.",
  },
  {
    id: "data-feed-gap-review",
    category: "Data / Source Ops",
    function: "Identify missing facts that materially affect ranking and trust",
    candidateAgent: "Listing Quality Gap Reviewer",
    currentOwner: "Founder + data ops",
    status: "candidate_for_agent",
    priority: "next",
    strategicImportance: "medium",
    requiredInputs: ["Listing fact coverage", "Approval outcomes", "Selector warnings"],
    expectedOutputs: ["Top missing-field patterns", "Impact notes", "Follow-up cleanup suggestions"],
    notes: "Should stay tightly scoped to decision-useful fields, not general enrichment sprawl.",
  },
  {
    id: "editorial-listing-selector",
    category: "Editorial / Content",
    function: "Select listings worth editorial attention",
    candidateAgent: "Agent V1 Listing Selector",
    currentOwner: "Live in admin",
    status: "in_progress",
    priority: "now",
    strategicImportance: "high",
    requiredInputs: ["Approved listings", "Trust signals", "Images", "Descriptions", "Location and price facts"],
    expectedOutputs: ["Ranked shortlist", "Selection reasons", "Theme", "Suggested angle"],
    notes: "Current narrow intelligence layer. Keep selection review-only.",
  },
  {
    id: "editorial-draft-generation",
    category: "Editorial / Content",
    function: "Turn approved selections into reviewable draft content",
    candidateAgent: "Draft Generator",
    currentOwner: "Live in admin",
    status: "in_progress",
    priority: "next",
    strategicImportance: "medium",
    requiredInputs: ["Selected listings", "Images", "Basic listing facts"],
    expectedOutputs: ["Draft caption", "Channel suggestion", "Hashtag suggestions"],
    notes: "Draft-to-approval only. No autoposting.",
  },
  {
    id: "seo-crawl-opportunity",
    category: "SEO / Market Intelligence",
    function: "Identify indexable listing and location opportunities",
    candidateAgent: "SEO Opportunity Mapper",
    currentOwner: "Founder + SEO",
    status: "human_plus_ai",
    priority: "next",
    strategicImportance: "high",
    requiredInputs: ["Indexable feed", "Crawl paths", "Location coverage", "SERP observations"],
    expectedOutputs: ["Opportunity clusters", "Page ideas", "Coverage gaps"],
    notes: "Useful once Agent V1 output is stable enough to inform targeted pages.",
  },
  {
    id: "seo-market-watch",
    category: "SEO / Market Intelligence",
    function: "Track market shifts visible in listing supply and pricing",
    candidateAgent: "Market Signal Watcher",
    currentOwner: "Founder",
    status: "candidate_for_agent",
    priority: "later",
    strategicImportance: "medium",
    requiredInputs: ["Listing universe snapshots", "Price changes", "Location mix", "Source mix"],
    expectedOutputs: ["Signal summary", "Potential story angles", "Watchlist items"],
    notes: "Should come after eval-backed selector trust is established.",
  },
  {
    id: "growth-distribution-planning",
    category: "Distribution / Growth",
    function: "Plan where selected content should be used and why",
    candidateAgent: "Distribution Planner",
    currentOwner: "Founder + editorial",
    status: "human_plus_ai",
    priority: "next",
    strategicImportance: "high",
    requiredInputs: ["Selected listings", "Content themes", "Channel constraints", "Campaign goals"],
    expectedOutputs: ["Channel-fit recommendation", "Distribution notes", "Priority queue"],
    notes: "Planning only. No publishing automation.",
  },
  {
    id: "growth-partner-outreach",
    category: "Distribution / Growth",
    function: "Support outreach to brokers, partners, and local amplifiers",
    candidateAgent: "Outreach Prep Assistant",
    currentOwner: "Founder",
    status: "candidate_for_agent",
    priority: "later",
    strategicImportance: "medium",
    requiredInputs: ["Partner list", "Offer context", "Selected listings", "Value proposition notes"],
    expectedOutputs: ["Outreach briefs", "Follow-up prompts", "Contact prioritization"],
    notes: "Only useful once offers and revenue priorities are clearer.",
  },
  {
    id: "founder-weekly-brief",
    category: "Founder / Decision Support",
    function: "Summarize what matters this week across sales, data, and content",
    candidateAgent: "Founder Briefing Copilot",
    currentOwner: "Founder",
    status: "candidate_for_agent",
    priority: "next",
    strategicImportance: "critical",
    requiredInputs: ["Sales notes", "Agent map", "Selector output", "Source issues", "Open decisions"],
    expectedOutputs: ["Weekly brief", "Priority stack", "Decision prompts"],
    notes: "Good planning layer because it joins revenue, operations, and editorial without creating automation sprawl.",
  },
  {
    id: "founder-roadmap-map",
    category: "Founder / Decision Support",
    function: "Keep the agent roadmap explicit instead of scattered across ad hoc interventions",
    candidateAgent: "Agent Map",
    currentOwner: "Founder + admin planning",
    status: "in_progress",
    priority: "now",
    strategicImportance: "critical",
    requiredInputs: ["Current initiatives", "Business priorities", "Open agent ideas", "Ownership notes"],
    expectedOutputs: ["Visible planning map", "Now/next/later view", "Strategic gaps"],
    notes: "This planning surface exists to reduce point-solution drift.",
  },
];
