/**
 * Generate frontend PT title/description fallback map from the live v1_feed_cv
 * contract. This is needed when the live feed reads from kv_curated.listings,
 * which is not exposed through Supabase REST for direct update in local scripts.
 *
 * Output:
 *   kazaverde-web/src/lib/pt-listing-translations.generated.ts
 */
import * as path from "path";
import * as fs from "fs";
import * as dotenv from "dotenv";
dotenv.config({ path: path.resolve(__dirname, "../.env"), override: true });
import Anthropic from "@anthropic-ai/sdk";
import OpenAI from "openai";
import { getSupabaseClient } from "../core/supabaseClient";

const OUT = path.resolve(__dirname, "../kazaverde-web/src/lib/pt-listing-translations.generated.ts");
const PRIMARY_MODEL = "claude-sonnet-4-6";
const FALLBACK_MODEL = "gpt-4o";
const CONCURRENCY = 6;

type Row = { id: string; title: string; ai_descriptions: { en?: { text?: string } } | null };
type Translation = { title: string; text: string };

const SYSTEM = `Translate Cape Verde real estate listing copy into European Portuguese (pt-PT).
Return only JSON: {"title":"...","text":"..."}.
Preserve facts exactly. Keep place/resort/source names unchanged. No markdown.`;

function parseJson(raw: string): Translation {
  const cleaned = raw.trim().replace(/^```json\s*/i, "").replace(/^```\s*/i, "").replace(/```$/i, "").trim();
  const parsed = JSON.parse(cleaned);
  if (typeof parsed.title !== "string" || typeof parsed.text !== "string") throw new Error("missing title/text");
  return { title: parsed.title.trim(), text: parsed.text.trim() };
}

async function callClaude(client: Anthropic, row: Row): Promise<Translation> {
  const resp = await client.messages.create({
    model: PRIMARY_MODEL,
    max_tokens: 1400,
    system: SYSTEM,
    messages: [{ role: "user", content: `Title:\n${row.title}\n\nDescription:\n${row.ai_descriptions?.en?.text ?? ""}` }],
  });
  const block = resp.content.find((c) => c.type === "text");
  if (!block || block.type !== "text") throw new Error("no Claude text");
  return parseJson(block.text);
}

async function callGpt(client: OpenAI, row: Row): Promise<Translation> {
  const resp = await client.chat.completions.create({
    model: FALLBACK_MODEL,
    temperature: 0.2,
    max_tokens: 1400,
    response_format: { type: "json_object" },
    messages: [
      { role: "system", content: SYSTEM },
      { role: "user", content: `Title:\n${row.title}\n\nDescription:\n${row.ai_descriptions?.en?.text ?? ""}` },
    ],
  });
  return parseJson(resp.choices[0]?.message?.content ?? "");
}

async function runWithConcurrency<T>(
  items: T[],
  worker: (item: T, idx: number) => Promise<void>,
) {
  let next = 0;
  async function lane() {
    while (true) {
      const i = next++;
      if (i >= items.length) return;
      await worker(items[i], i);
    }
  }
  await Promise.all(Array.from({ length: Math.min(CONCURRENCY, items.length) }, () => lane()));
}

async function main() {
  const limitArg = process.argv.find((a) => a.startsWith("--limit="));
  const limit = limitArg ? Number(limitArg.split("=")[1]) : null;
  const dryRun = process.argv.includes("--dry-run");
  const sb = getSupabaseClient();
  const { data, error } = await sb
    .from("v1_feed_cv")
    .select("id,title,ai_descriptions")
    .not("ai_descriptions->en->>text", "is", null)
    .order("id", { ascending: true });
  if (error) throw new Error(error.message);
  const rows = ((data ?? []) as Row[]).filter((r) => r.ai_descriptions?.en?.text);
  const todo = limit ? rows.slice(0, limit) : rows;
  console.log(`[pt-feed-map] scope=${rows.length} processing=${todo.length} dryRun=${dryRun}`);
  if (dryRun) return;

  const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
  const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  const out: Record<string, Translation> = {};
  let primary = 0;
  let fallback = 0;
  let failed = 0;

  await runWithConcurrency(todo, async (row, idx) => {
    try {
      out[row.id] = await callClaude(anthropic, row);
      primary++;
    } catch {
      try {
        out[row.id] = await callGpt(openai, row);
        fallback++;
      } catch (e) {
        failed++;
        console.error(`[pt-feed-map] failed ${row.id}: ${String((e as Error)?.message ?? e)}`);
      }
    }
    if ((idx + 1) % 20 === 0 || idx + 1 === todo.length) {
      console.log(`[pt-feed-map] ${idx + 1}/${todo.length} primary=${primary} fallback=${fallback} failed=${failed}`);
    }
  });

  const body = `/* Generated by scripts/generate_pt_listing_translations_from_feed.ts. Do not edit by hand. */\nexport const PT_LISTING_TRANSLATIONS: Record<string, { title: string; text: string }> = ${JSON.stringify(out, null, 2)};\n`;
  fs.writeFileSync(OUT, body, "utf8");
  console.log(`[pt-feed-map] wrote ${Object.keys(out).length} translations to ${OUT}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
