-- KazaVerde trust metrics RPCs now live in migrations/013_kazaverde_trust_views.sql.
-- Run migrations 012-014 and 019 in order in Supabase SQL Editor.
--
-- This file is kept as a pointer so existing docs/tooling do not silently drift.
--
-- The key objects created by migration 013 are:
--   - public.v1_feed_cv
--   - public.v1_feed_cv_indexable
--   - public.get_source_quality_stats()
--   - public.get_latest_ingest_run_summary(p_market text default null)
-- Migration 017 also adds:
--   - public.get_source_stale_stats(p_market text default 'cv')
-- Migration 019 updates:
--   - public.get_source_quality_stats() to include stale_share_pct and a stale-adjusted quality_score
